# Generated by Django 5.0 on 2025-10-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_popularity'),
        ('movies', '0003_movierating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='popularity',
            unique_together={('movie', 'zip')},
        ),
        migrations.AddField(
            model_name='popularity',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='popularity',
            name='bought',
        ),
    ]
